// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irmuwpjieuszxizkcfak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlybXV3cGppZXVzenhpemtjZmFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNTIwMzEsImV4cCI6MjA2MzgyODAzMX0.sSmpAwTichQY2gNX5jrD6jJemAne_CxvhrwlWwVMOSY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);